package uk.co.edgewords.iocodemo.Tests;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;



import static org.hamcrest.CoreMatchers.is;


import org.hamcrest.MatcherAssert;
import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import uk.co.edgewords.iocodemo.Utilities.BaseTest;

public class SelIDETestTest extends BaseTest {



  @Test
  public void selIDETest() {
    // Test name: SelIDETest
    // Step # | name | target | value
    // 1 | open | /webdriver2/ | 
    driver.get("https://www.edgewordstraining.co.uk/webdriver2/");
    // 2 | setWindowSize | 1201x1047 | 
    driver.manage().window().setSize(new Dimension(1201, 1047));
    // 3 | click | css=.last span | 
    driver.findElement(By.cssSelector(".last span")).click();
    // 4 | click | css=li:nth-child(3) span | 
    driver.findElement(By.cssSelector("li:nth-child(3) span")).click();
    // 5 | click | id=textInput | 
    driver.findElement(By.id("textInput")).click();
    // 6 | type | id=textInput | Steve Powell
    driver.findElement(By.id("textInput")).sendKeys("Steve Powell");
    // 7 | click | id=textArea | 
    driver.findElement(By.id("textArea")).click();
    // 8 | click | id=textArea | 
    driver.findElement(By.id("textArea")).click();
    // 9 | type | id=textArea | More text\nin here\n
    driver.findElement(By.id("textArea")).sendKeys("More text\\nin here\\n");
    // 10 | click | id=checkbox | 
    driver.findElement(By.id("checkbox")).click();
    // 11 | click | id=select | 
    driver.findElement(By.id("select")).click();
    // 12 | select | id=select | label=Selection Two
    {
      WebElement dropdown = driver.findElement(By.id("select"));
      dropdown.findElement(By.xpath("//option[. = 'Selection Two']")).click();
    }
    // 13 | click | id=two | 
    driver.findElement(By.id("two")).click();
    // 14 | click | linkText=Submit | 
    driver.findElement(By.linkText("Submit")).click();
    // 15 | click | css=tr:nth-child(2) > td:nth-child(3) | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).click();
    // 16 | assertText | id=textInputValue | Steve Powell
    MatcherAssert.assertThat(driver.findElement(By.id("textInputValue")).getText(), is("Steve Powell"));
    System.out.println("Finished");

  }
}
